### ISSUE TITLE
iterative alignment scheme only for sliding window model?

### ISSUE THREAD

**Issue by qtct** [redrock303/Revisiting-Temporal-Alignment-for-Video-Restoration#12]
The article mentioned that the iterative alignment scheme can be applied to IconVSR, but the network structure in the code is based on sliding window, so how can this iterative alignment scheme be inserted into the network model based on recurrent structure.

**Comment by redrock303** [comment]
As you can see, IconVSR proposes an information-Refill module. Like the EDVR, it uses five local frames (AKA sliding window scheme) and performs temporal aggregation independently. Instead, we opt for it and perform iterative aggregation.

**Comment by qtct** [comment]
> Thanks for your reply, I get it.
