### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by xiaomingxige** [redrock303/Revisiting-Temporal-Alignment-for-Video-Restoration#3]
BasicVSR++ only has 6.4M parameters

**Comment by redrock303** [comment]
According to their paper, BasicVSR++ small has 6.4M parameters. The model that achieves 37.79dB owns 7.3M parameters, which is pre-trained using REDS dataset.

**Comment by xiaomingxige** [comment]
How much PSNR can you achieve if you are pre-trained using REDS dataset?

**Comment by redrock303** [comment]
For a fair comparison with most VSR methods (EDVR, MuCAN,..), we just train our model using the Vimeo-90K dataset. We will explore the benefits by using additional REDS dataset. Thanks for your good suggestion.
