### ISSUE TITLE
Adaptive Re-weighting in Section 3.4 Eq 9-13

### ISSUE THREAD

**Issue by Magauiya** [redrock303/Revisiting-Temporal-Alignment-for-Video-Restoration#6]
Dear authors,

I am very interested in your work and would appreciate if you find time to answer the following questions:

1. As far as I understand, ARW block generates "refined aligned feature" for each frame feature k in {-N, N} set (see Eq 9-13). However, after such operator, how do you fuse all 2N+1 features into a single one?
2. What is the "Reconstruction" module? What is the input for this module? 
3. In ablation studies, you have added "Baseline" model without IAM and ARW. However, it is not clear what operators have been utilized to fuse frame features? Do you simply concatenate features from frames without alignment? 

Thank you!

**Comment by Magauiya** [comment]
Also,
4. Under the Eq 12, it is mentioned that **C_k** has the same shape as **F_k hat**. Does it mean that L_2 norm in Eq.2 between **F_k** and **F_avg** is elementwise?
5. Have you tried to learn alpha parameter?

**Comment by redrock303** [comment]
1. We just use the calculated adaptive weights and use them to re-weighting each temporally aligned feature. Therefore, we still have 2N aligned neighboring features. 
2. Our Reconstruction module consists of several stacked residual blocks. Specifically, we include a single convolution to fuse all 2N+1 features into a single one to reduce the channel dimension(2N+1 x C ->C).
3. In our baseline, we use the same sub-alignment structure to perform a progressive alignment pipeline(without refinement steps). Also, we simply drop the ARW module. So we also concatenate those **aligned** features from frames.
4. Yes, it does. We calculate the elementwise differences between each aligned feature with their average to obtain the temporal consistency factor.
5. We make a simple parameter search~(-0.5,-1.0,-2.0) to find a better alpha parameter. But I think it will be better to take end-to-end learning for deciding the alpha.
