### ISSUE TITLE
Iterative Alignment Module in Section 3.3

### ISSUE THREAD

**Issue by wdmwhh** [redrock303/Revisiting-Temporal-Alignment-for-Video-Restoration#8]
Thanks for your great job. It is kind for you to answer the following questions:
1. Does IAM explore the optical flows produced by SpyNet or RAFT?
2. Does IconVSR+IAM denote "replace `optical flow for spatial alignment` (including SpyNet) with IAM"?
3. Does Iterative Number 3 in IAM mean "t<sub>max</sub>=3", and is the total number of sub-alignments less than N(N+1)?
4. Does DConv in Section 3.3.3 Eq 7,8 work the same as first-order flow-guided deformable alignment in BasicVSR++? Specifically, the estimated motion field h is served as the pre-offsets of deformable conv.

**Comment by redrock303** [comment]
1. We have not explored the optical flows. In our ablation study section, we just use the RAFT for evaluating the accuracy of the results produced by different iterative numbers.
2. Yes, we use the proposed IAM for performing the spatial alignment.

**Comment by wdmwhh** [comment]
Thanks for your quick reply. I'm sorry to ask two more questions:
1. Does Iterative Number 3 in IAM mean "t<sub>max</sub>=3", and is the total number of sub-alignments less than N(N+1)?
4. Does DConv in Section 3.3.3 Eq 7,8 work the same as first-order flow-guided deformable alignment in BasicVSR++? Specifically, the estimated motion field h is served as the pre-offsets of deformable conv.

**Comment by redrock303** [comment]
1. Yes, it is. The maximum iterative number will not be larger than the one-side frame number (t_max<N). As we described in our paper, we conduct the two-side alignments separately.({1,2,3->0} and {-1,-2,-3->0}).
2. We do not use optical flow fields for guidance, we just regard the estimated motion field h as an implicit feature that represents the motion information between two frames (h is used to decode the offsets in DCN).
You are welcome to raise any further problems.

**Comment by wdmwhh** [comment]
Thanks again. Could I think that h is 128-d features instead of 2-d offsets and is served as extra_feat for DConv? Is DConv [ModulatedDCNPack](https://github.com/open-mmlab/mmediting/blob/master/mmedit/models/backbones/sr_backbones/edvr_net.py#L15)?

**Comment by redrock303** [comment]
Yes, you are right.
